# Generated by Django 5.0 on 2024-02-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Cordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.IntegerField()),
                ('id_plano_proveedor', models.IntegerField()),
                ('id_poly', models.IntegerField()),
                ('coords', models.CharField(max_length=21800)),
            ],
            options={
                'db_table': 'Cordenadas',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('clave', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('lenguaje', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Tipo_Lugar',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=250)),
                ('fecha_publicado', models.DateTimeField()),
                ('fecha_aceptado', models.DateTimeField()),
                ('fecha_tomado', models.DateTimeField()),
                ('fecha_atendido', models.DateTimeField()),
                ('estatus', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
            ],
            options={
                'db_table': 'Incidente',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=250)),
                ('colonia', models.CharField(max_length=250)),
                ('cp', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=250)),
                ('estatus', models.BooleanField(default=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
            ],
            options={
                'db_table': 'Lugar',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('clave', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=50, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estado')),
            ],
            options={
                'db_table': 'Municipio',
            },
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.pais'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField()),
                ('nombre', models.CharField(blank=True, max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('estatus', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.categoria')),
            ],
            options={
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.municipio')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.proveedor')),
            ],
            options={
                'db_table': 'Cobertura',
            },
        ),
        migrations.CreateModel(
            name='Rel_Incidente_Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.incidente')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.lugar')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipo_lugar')),
            ],
            options={
                'db_table': 'Rel_Incidente_Lugar',
            },
        ),
    ]
